/* automatically generated from xfce4-session-settings.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfce4_session_settings_ui)
#endif
#ifdef __GNUC__
static const char xfce4_session_settings_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfce4_session_settings_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.20\"/><object class=\"GtkDialog\" id=\"dialog_saving\""
  "><property name=\"can_focus\">False</property><property name=\"border_w"
  "idth\">5</property><property name=\"title\" translatable=\"yes\">Saving"
  " Session</property><property name=\"resizable\">False</property><proper"
  "ty name=\"window_position\">center-on-parent</property><property name=\""
  "destroy_with_parent\">True</property><property name=\"icon_name\">xfce4"
  "-session</property><property name=\"type_hint\">dialog</property><prope"
  "rty name=\"skip_taskbar_hint\">True</property><property name=\"skip_pag"
  "er_hint\">True</property><property name=\"transient_for\">xfce4_session"
  "_settings_dialog</property><child internal-child=\"vbox\"><object class"
  "=\"GtkVBox\" id=\"dialog-vbox2\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"spaci"
  "ng\">2</property><child internal-child=\"action_area\"><object class=\""
  "GtkHButtonBox\" id=\"dialog-action_area2\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"layout_style\">end</property><child><object class=\"GtkButton\" id"
  "=\"button3\"><property name=\"label\">gtk-close</property><property nam"
  "e=\"use_action_appearance\">False</property><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><property na"
  "me=\"receives_default\">True</property><property name=\"use_stock\">Tru"
  "e</property></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">False</property><property name=\"position\">0<"
  "/property></packing></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"pack_type\">end</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkVBox\" id=\"vbox5\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"border_width\">6</property><property name=\"spac"
  "ing\">6</property><child><object class=\"GtkHBox\" id=\"hbox8\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"spacing\">12</property><child><object class=\""
  "GtkImage\" id=\"image6\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"stock\">gtk-d"
  "ialog-info</property><property name=\"icon-size\">6</property></object>"
  "<packing><property name=\"expand\">False</property><property name=\"fil"
  "l\">True</property><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkLabel\" id=\"label10\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"xalign\">0</property><property name=\"label\" translata"
  "ble=\"yes\">Your session is being saved.  If you do not wish to wait, y"
  "ou may close this window.</property><property name=\"justify\">fill</pr"
  "operty><property name=\"wrap\">True</property></object><packing><proper"
  "ty name=\"expand\">True</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">1</property></packing></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkProgressBar\" id=\"progress_save_session\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"activity_mode\">True</property></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">1</pro"
  "perty></packing></child></object></child><action-widgets><action-widget"
  " response=\"0\">button3</action-widget></action-widgets></object><objec"
  "t class=\"XfceTitledDialog\" id=\"xfce4_session_settings_dialog\"><prop"
  "erty name=\"can_focus\">False</property><property name=\"title\" transl"
  "atable=\"yes\">Session and Startup</property><property name=\"window_po"
  "sition\">center-on-parent</property><property name=\"icon_name\">xfce4-"
  "session</property><property name=\"type_hint\">dialog</property><proper"
  "ty name=\"subtitle\" translatable=\"yes\">Customize desktop startup and"
  " splash screen</property><child internal-child=\"vbox\"><object class=\""
  "GtkVBox\" id=\"dialog-vbox1\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"spacing\""
  ">2</property><child internal-child=\"action_area\"><object class=\"GtkH"
  "ButtonBox\" id=\"dialog-action_area1\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><child><object c"
  "lass=\"GtkButton\" id=\"button1\"><property name=\"label\">gtk-help</pr"
  "operty><property name=\"use_action_appearance\">False</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">True</property><property na"
  "me=\"use_stock\">True</property></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">False</property><property "
  "name=\"position\">0</property></packing></child><child><object class=\""
  "GtkButton\" id=\"button2\"><property name=\"label\">gtk-close</property"
  "><property name=\"use_action_appearance\">False</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"receives_default\">True</property><property name=\"u"
  "se_stock\">True</property></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">False</property><property name=\""
  "position\">1</property></packing></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"pack_type\">end</property><property name=\"position\">0<"
  "/property></packing></child><child><object class=\"GtkNotebook\" id=\"p"
  "lug-child\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"border_width\">6</property>"
  "<child><object class=\"GtkVBox\" id=\"vbox1\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"border_width\">12</property><property name=\"spacing\">6</proper"
  "ty><child><object class=\"GtkFrame\" id=\"frame1\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"label_xalign\">0</property><property name=\"shadow_type\">"
  "none</property><child><object class=\"GtkAlignment\" id=\"alignment2\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"top_padding\">6</property><property na"
  "me=\"bottom_padding\">6</property><property name=\"left_padding\">12</p"
  "roperty><child><object class=\"GtkCheckButton\" id=\"chk_display_choose"
  "r\"><property name=\"label\" translatable=\"yes\">_Display chooser on l"
  "ogin</property><property name=\"use_action_appearance\">False</property"
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">False</property><pr"
  "operty name=\"tooltip_text\" translatable=\"yes\">Display the session c"
  "hooser every time Xfce starts</property><property name=\"use_underline\""
  ">True</property><property name=\"draw_indicator\">True</property></obje"
  "ct></child></object></child><child type=\"label\"><object class=\"GtkLa"
  "bel\" id=\"label6\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"label\" translatab"
  "le=\"yes\">&lt;b&gt;Session Chooser&lt;/b&gt;</property><property name="
  "\"use_markup\">True</property></object></child></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkFrame\" id=\"frame2\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "label_xalign\">0</property><property name=\"shadow_type\">none</propert"
  "y><child><object class=\"GtkAlignment\" id=\"alignment3\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"top_padding\">6</property><property name=\"bottom_p"
  "adding\">6</property><property name=\"left_padding\">12</property><chil"
  "d><object class=\"GtkVBox\" id=\"vbox2\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"spacing\">6</property><child><object class=\"GtkCheckButton\" id=\"c"
  "hk_session_autosave\"><property name=\"label\" translatable=\"yes\">Aut"
  "omatically save session on logo_ut</property><property name=\"use_actio"
  "n_appearance\">False</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"receives"
  "_default\">False</property><property name=\"tooltip_text\" translatable"
  "=\"yes\">Always save the session when logging out</property><property n"
  "ame=\"use_underline\">True</property><property name=\"draw_indicator\">"
  "True</property></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "0</property></packing></child><child><object class=\"GtkCheckButton\" i"
  "d=\"chk_logout_prompt\"><property name=\"label\" translatable=\"yes\">P"
  "ro_mpt on logout</property><property name=\"use_action_appearance\">Fal"
  "se</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"tooltip_text\" translatable=\"yes\">Prompt for"
  " confirmation when logging out</property><property name=\"use_underline"
  "\">True</property><property name=\"active\">True</property><property na"
  "me=\"draw_indicator\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"position\">1</property></packing></child></object></child></o"
  "bject></child><child type=\"label\"><object class=\"GtkLabel\" id=\"lab"
  "el7\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"label\" translatable=\"yes\">&lt"
  ";b&gt;Logout Settings&lt;/b&gt;</property><property name=\"use_markup\""
  ">True</property></object></child></object><packing><property name=\"exp"
  "and\">True</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">1</property></packing></child></object></child><child "
  "type=\"tab\"><object class=\"GtkLabel\" id=\"label1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">_General</property><proper"
  "ty name=\"use_underline\">True</property></object><packing><property na"
  "me=\"tab_fill\">False</property></packing></child><child><object class="
  "\"GtkHBox\" id=\"hbox2\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"border_width\""
  ">12</property><property name=\"spacing\">12</property><child><object cl"
  "ass=\"GtkVBox\" id=\"vbox6\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"spacing\""
  ">6</property><child><object class=\"GtkScrolledWindow\" id=\"scrolledwi"
  "ndow2\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"hscrollbar_policy\">automatic</"
  "property><property name=\"vscrollbar_policy\">automatic</property><prop"
  "erty name=\"shadow_type\">etched-in</property><child><object class=\"Gt"
  "kTreeView\" id=\"treeview_splash\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"head"
  "ers_visible\">False</property></object></child></object><packing><prope"
  "rty name=\"expand\">True</property><property name=\"fill\">True</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkButton\" id=\"btn_splash_configure\"><property name=\"u"
  "se_action_appearance\">False</property><property name=\"visible\">True<"
  "/property><property name=\"sensitive\">False</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">True</pr"
  "operty><property name=\"tooltip_text\" translatable=\"yes\">Opens the c"
  "onfiguration panel for the selected splash screen</property><child><obj"
  "ect class=\"GtkHBox\" id=\"hbox3\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"spa"
  "cing\">4</property><child><object class=\"GtkImage\" id=\"image2\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"xalign\">1</property><property name=\"stoc"
  "k\">gtk-preferences</property></object><packing><property name=\"expand"
  "\">True</property><property name=\"fill\">True</property><property name"
  "=\"position\">0</property></packing></child><child><object class=\"GtkL"
  "abel\" id=\"label11\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"xalign\">0</prop"
  "erty><property name=\"label\" translatable=\"yes\">Con_figure</property"
  "><property name=\"use_underline\">True</property><property name=\"mnemo"
  "nic_widget\">btn_splash_configure</property></object><packing><property"
  " name=\"expand\">True</property><property name=\"fill\">True</property>"
  "<property name=\"position\">1</property></packing></child></object></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">1</property"
  "></packing></child><child><object class=\"GtkButton\" id=\"btn_splash_t"
  "est\"><property name=\"use_action_appearance\">False</property><propert"
  "y name=\"visible\">True</property><property name=\"sensitive\">False</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">True</property><property name=\"tooltip_text\" transla"
  "table=\"yes\">Demonstrates the selected splash screen</property><child>"
  "<object class=\"GtkHBox\" id=\"hbox4\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "spacing\">4</property><child><object class=\"GtkImage\" id=\"image3\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"xalign\">1</property><property name=\"s"
  "tock\">gtk-execute</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkLabe"
  "l\" id=\"label12\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"xalign\">0</propert"
  "y><property name=\"label\" translatable=\"yes\">_Test</property><proper"
  "ty name=\"use_underline\">True</property><property name=\"mnemonic_widg"
  "et\">btn_splash_test</property></object><packing><property name=\"expan"
  "d\">True</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">1</property></packing></child></object></child></object>"
  "<packing><property name=\"expand\">False</property><property name=\"fil"
  "l\">True</property><property name=\"position\">2</property></packing></"
  "child></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkVBox\" id=\"vbox7\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"spacing\">6</property><child><object class"
  "=\"GtkImage\" id=\"img_splash_preview\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"stock\">gtk-missing-image</property></object><packing><property name="
  "\"expand\">True</property><property name=\"fill\">True</property><prope"
  "rty name=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkFrame\" id=\"frame5\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"label_xal"
  "ign\">0</property><child><object class=\"GtkAlignment\" id=\"alignment6"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"bottom_padding\">4</property><prope"
  "rty name=\"left_padding\">12</property><child><object class=\"GtkTable\""
  " id=\"table1\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"n_rows\">4</property><p"
  "roperty name=\"n_columns\">2</property><property name=\"column_spacing\""
  ">12</property><property name=\"row_spacing\">2</property><child><object"
  " class=\"GtkLabel\" id=\"lbl_splash_desc0\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"xalign\">0</property><property name=\"label\" translatable=\"yes\""
  ">&lt;b&gt;Description:&lt;/b&gt;</property><property name=\"use_markup\""
  ">True</property></object><packing><property name=\"x_options\">GTK_FILL"
  "</property></packing></child><child><object class=\"GtkLabel\" id=\"lbl"
  "_splash_version0\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"xalign\">0</propert"
  "y><property name=\"label\" translatable=\"yes\">&lt;b&gt;Version:&lt;/b"
  "&gt;</property><property name=\"use_markup\">True</property></object><p"
  "acking><property name=\"top_attach\">1</property><property name=\"botto"
  "m_attach\">2</property><property name=\"x_options\">GTK_FILL</property>"
  "</packing></child><child><object class=\"GtkLabel\" id=\"lbl_splash_aut"
  "hor0\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"xalign\">0</property><property "
  "name=\"label\" translatable=\"yes\">&lt;b&gt;Author:&lt;/b&gt;</propert"
  "y><property name=\"use_markup\">True</property></object><packing><prope"
  "rty name=\"top_attach\">2</property><property name=\"bottom_attach\">3<"
  "/property><property name=\"x_options\">GTK_FILL</property></packing></c"
  "hild><child><object class=\"GtkLabel\" id=\"lbl_splash_homepage0\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"xalign\">0</property><property name=\"labe"
  "l\" translatable=\"yes\">&lt;b&gt;Homepage:&lt;/b&gt;</property><proper"
  "ty name=\"use_markup\">True</property></object><packing><property name="
  "\"top_attach\">3</property><property name=\"bottom_attach\">4</property"
  "><property name=\"x_options\">GTK_FILL</property></packing></child><chi"
  "ld><object class=\"GtkLabel\" id=\"lbl_splash_desc1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"xalign\">0</property><property name=\"label\" translata"
  "ble=\"yes\">label</property><property name=\"selectable\">True</propert"
  "y></object><packing><property name=\"left_attach\">1</property><propert"
  "y name=\"right_attach\">2</property></packing></child><child><object cl"
  "ass=\"GtkLabel\" id=\"lbl_splash_version1\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"xalign\">0</property><property name=\"label\" translatable=\"yes\""
  ">label</property><property name=\"selectable\">True</property></object>"
  "<packing><property name=\"left_attach\">1</property><property name=\"ri"
  "ght_attach\">2</property><property name=\"top_attach\">1</property><pro"
  "perty name=\"bottom_attach\">2</property></packing></child><child><obje"
  "ct class=\"GtkLabel\" id=\"lbl_splash_author1\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"xalign\">0</property><property name=\"label\" translatable=\""
  "yes\">label</property><property name=\"selectable\">True</property></ob"
  "ject><packing><property name=\"left_attach\">1</property><property name"
  "=\"right_attach\">2</property><property name=\"top_attach\">2</property"
  "><property name=\"bottom_attach\">3</property></packing></child><child>"
  "<object class=\"GtkLabel\" id=\"lbl_splash_homepage1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"xalign\">0</property><property name=\"label\" translata"
  "ble=\"yes\">label</property><property name=\"selectable\">True</propert"
  "y></object><packing><property name=\"left_attach\">1</property><propert"
  "y name=\"right_attach\">2</property><property name=\"top_attach\">3</pr"
  "operty><property name=\"bottom_attach\">4</property></packing></child><"
  "/object></child></object></child><child type=\"label\"><object class=\""
  "GtkLabel\" id=\"label13\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"label\" tran"
  "slatable=\"yes\">&lt;b&gt;Information&lt;/b&gt;</property><property nam"
  "e=\"use_markup\">True</property></object></child></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">1</property></packing></child></objec"
  "t><packing><property name=\"expand\">True</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">1</property></packing><"
  "/child></object><packing><property name=\"position\">1</property></pack"
  "ing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label2\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">S_plash<"
  "/property><property name=\"use_underline\">True</property></object><pac"
  "king><property name=\"position\">1</property><property name=\"tab_fill\""
  ">False</property></packing></child><child><object class=\"GtkVBox\" id="
  "\"vbox8\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"border_width\">12</property>"
  "<property name=\"spacing\">6</property><child><object class=\"GtkHBox\""
  " id=\"hbox10\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"spacing\">12</property>"
  "<child><object class=\"GtkImage\" id=\"image10\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"stock\">gtk-dialog-info</property><property name=\"icon-size"
  "\">6</property></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "0</property></packing></child><child><object class=\"GtkLabel\" id=\"la"
  "bel21\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"xalign\">0</property><property"
  " name=\"label\" translatable=\"yes\">These applications are a part of t"
  "he currently-running session, and can be saved when you log out.  Chang"
  "es below will only take effect when the session is saved.</property><pr"
  "operty name=\"justify\">fill</property><property name=\"wrap\">True</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">1</prope"
  "rty></packing></child></object><packing><property name=\"expand\">False"
  "</property><property name=\"fill\">True</property><property name=\"posi"
  "tion\">0</property></packing></child><child><object class=\"GtkScrolled"
  "Window\" id=\"scrolledwindow4\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"hscroll"
  "bar_policy\">automatic</property><property name=\"vscrollbar_policy\">a"
  "utomatic</property><property name=\"shadow_type\">etched-in</property><"
  "child><object class=\"GtkTreeView\" id=\"treeview_clients\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">True</prope"
  "rty></object></child></object><packing><property name=\"expand\">True</"
  "property><property name=\"fill\">True</property><property name=\"positi"
  "on\">1</property></packing></child><child><object class=\"GtkHBox\" id="
  "\"hbox7\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"spacing\">6</property><child"
  "><object class=\"GtkButton\" id=\"btn_save_session\"><property name=\"u"
  "se_action_appearance\">False</property><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property><child><object class=\"GtkHBox\" id=\""
  "hbox5\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"spacing\">4</property><child><"
  "object class=\"GtkImage\" id=\"image4\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"xalign\">1</property><property name=\"stock\">gtk-save</property></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkLabel\" id=\"label5\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"xalign\">0</property><property name=\"label\" transl"
  "atable=\"yes\">Save Sess_ion</property><property name=\"use_underline\""
  ">True</property></object><packing><property name=\"expand\">True</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "1</property></packing></child></object></child></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">1</property></packing></child><child><o"
  "bject class=\"GtkButton\" id=\"btn_clear_sessions\"><property name=\"us"
  "e_action_appearance\">False</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">True</property><property name=\"tooltip_text\" transl"
  "atable=\"yes\">Empty the session cache</property><child><object class=\""
  "GtkHBox\" id=\"hbox9\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"spacing\">4</pr"
  "operty><child><object class=\"GtkImage\" id=\"image7\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"xalign\">1</property><property name=\"stock\">gtk-clear"
  "</property></object><packing><property name=\"expand\">True</property><"
  "property name=\"fill\">True</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkLabel\" id=\"label24"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"xalign\">0</property><property name"
  "=\"label\" translatable=\"yes\">Clear save_d sessions</property><proper"
  "ty name=\"use_underline\">True</property></object><packing><property na"
  "me=\"expand\">True</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">1</property></packing></child></object></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"position\">1</property></"
  "packing></child><child><object class=\"GtkButton\" id=\"btn_quit_client"
  "\"><property name=\"use_action_appearance\">False</property><property n"
  "ame=\"visible\">True</property><property name=\"sensitive\">False</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">True</property><property name=\"tooltip_text\" translatab"
  "le=\"yes\">Quit the program, and remove it from the session</property><"
  "child><object class=\"GtkHBox\" id=\"hbox6\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"spacing\">4</property><child><object class=\"GtkImage\" id=\"ima"
  "ge5\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"xalign\">1</property><property n"
  "ame=\"stock\">gtk-quit</property></object><packing><property name=\"exp"
  "and\">True</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">0</property></packing></child><child><object class=\"G"
  "tkLabel\" id=\"label23\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"xalign\">0</p"
  "roperty><property name=\"label\" translatable=\"yes\">_Quit Program</pr"
  "operty><property name=\"use_underline\">True</property></object><packin"
  "g><property name=\"expand\">True</property><property name=\"fill\">True"
  "</property><property name=\"position\">1</property></packing></child></"
  "object></child></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">True</property><property name=\"pack_type\""
  ">end</property><property name=\"position\">1</property></packing></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">True</property><property name=\"position\">2</property><"
  "/packing></child></object><packing><property name=\"position\">2</prope"
  "rty></packing></child><child type=\"tab\"><object class=\"GtkLabel\" id"
  "=\"label3\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">Sessio_n</property><property name=\"use_underline\">True</property><"
  "/object><packing><property name=\"position\">2</property><property name"
  "=\"tab_fill\">False</property></packing></child><child><object class=\""
  "GtkVBox\" id=\"vbox3\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"border_width\">"
  "12</property><property name=\"spacing\">6</property><child><object clas"
  "s=\"GtkFrame\" id=\"frame3\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"label_xal"
  "ign\">0</property><property name=\"shadow_type\">none</property><child>"
  "<object class=\"GtkAlignment\" id=\"alignment4\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"top_padding\">6</property><property name=\"bottom_padding\">"
  "6</property><property name=\"left_padding\">12</property><child><object"
  " class=\"GtkVBox\" id=\"vbox4\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"spacin"
  "g\">6</property><child><object class=\"GtkCheckButton\" id=\"chk_compat"
  "_gnome\"><property name=\"label\" translatable=\"yes\">Launch GN_OME se"
  "rvices on startup</property><property name=\"use_action_appearance\">Fa"
  "lse</property><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"receives_default\">False<"
  "/property><property name=\"tooltip_text\" translatable=\"yes\">Start GN"
  "OME services, such as gnome-keyring</property><property name=\"use_unde"
  "rline\">True</property><property name=\"draw_indicator\">True</property"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"position\">0</property></"
  "packing></child><child><object class=\"GtkCheckButton\" id=\"chk_compat"
  "_kde\"><property name=\"label\" translatable=\"yes\">Launch _KDE servic"
  "es on startup</property><property name=\"use_action_appearance\">False<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">False</pro"
  "perty><property name=\"tooltip_text\" translatable=\"yes\">Start KDE se"
  "rvices, such as kdeinit</property><property name=\"use_underline\">True"
  "</property><property name=\"draw_indicator\">True</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object></child></object></child><child type=\"label\"><object clas"
  "s=\"GtkLabel\" id=\"label8\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"label\" t"
  "ranslatable=\"yes\">&lt;b&gt;Compatibility&lt;/b&gt;</property><propert"
  "y name=\"use_markup\">True</property></object></child></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">True"
  "</property><property name=\"position\">0</property></packing></child><c"
  "hild><object class=\"GtkFrame\" id=\"frame4\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label_xalign\">0</property><property name=\"shadow_type\">none</"
  "property><child><object class=\"GtkAlignment\" id=\"alignment5\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"top_padding\">6</property><property name=\"b"
  "ottom_padding\">6</property><property name=\"left_padding\">12</propert"
  "y><child><object class=\"GtkCheckButton\" id=\"chk_enable_tcp\"><proper"
  "ty name=\"label\" translatable=\"yes\">Manage _remote applications</pro"
  "perty><property name=\"use_action_appearance\">False</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">False</property><property na"
  "me=\"tooltip_text\" translatable=\"yes\">Manage remote applications ove"
  "r the network (this may be a security risk)</property><property name=\""
  "use_underline\">True</property><property name=\"draw_indicator\">True</"
  "property></object></child></object></child><child type=\"label\"><objec"
  "t class=\"GtkLabel\" id=\"label9\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lab"
  "el\" translatable=\"yes\">&lt;b&gt;Security&lt;/b&gt;</property><proper"
  "ty name=\"use_markup\">True</property></object></child></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">1</property></packing></child><"
  "child><object class=\"GtkFrame\" id=\"frame6\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"label_xalign\">0</property><property name=\"shadow_type\">none"
  "</property><child><object class=\"GtkAlignment\" id=\"alignment7\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"top_padding\">6</property><property name=\""
  "bottom_padding\">6</property><property name=\"left_padding\">12</proper"
  "ty><child><object class=\"GtkCheckButton\" id=\"chk_lock_screen\"><prop"
  "erty name=\"label\" translatable=\"yes\">Lock screen be_fore sleep</pro"
  "perty><property name=\"use_action_appearance\">False</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">False</property><property na"
  "me=\"tooltip_text\" translatable=\"yes\">Run xflock4 before suspending "
  "or hibernating the system</property><property name=\"use_underline\">Tr"
  "ue</property><property name=\"draw_indicator\">True</property></object>"
  "</child></object></child><child type=\"label\"><object class=\"GtkLabel"
  "\" id=\"label25\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"label\" translatable"
  "=\"yes\">&lt;b&gt;Shutdown&lt;/b&gt;</property><property name=\"use_mar"
  "kup\">True</property></object></child></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">2</property></packing></child></object><packing>"
  "<property name=\"position\">3</property></packing></child><child type=\""
  "tab\"><object class=\"GtkLabel\" id=\"label4\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"label\" translatable=\"yes\">Ad_vanced</property><property nam"
  "e=\"use_underline\">True</property></object><packing><property name=\"p"
  "osition\">3</property><property name=\"tab_fill\">False</property></pac"
  "king></child></object><packing><property name=\"expand\">True</property"
  "><property name=\"fill\">True</property><property name=\"position\">1</"
  "property></packing></child></object></child><action-widgets><action-wid"
  "get response=\"-11\">button1</action-widget><action-widget response=\"-"
  "7\">button2</action-widget></action-widgets></object></interface>"
};

static const unsigned xfce4_session_settings_ui_length = 34143u;

